<?php

function kay_master_update_7002() {
  module_enable(array(
    'views_data_export',
    'feature_basic_structure',
    'feature_events_and_registration',
    'feature_pages'
  ));
}

function kay_master_update_7003() {
  module_enable(array(
    'context'
  ));
}

function kay_master_update_7004() {
  module_enable(array(
    'user_mailman_register'
  ));
}

function kay_master_update_7004() {
  module_enable(array(
    'feature_board_member_list'
  ));
}
